<?php

use Illuminate\Database\Seeder;

class ComunasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comunas')->insert(['nombre' =>'ARICA', 'region_id' => 15]);
        DB::table('comunas')->insert(['nombre' =>'IQUIQUE', 'region_id' => 1]);
        DB::table('comunas')->insert(['nombre' =>'HUARA', 'region_id' => 1]);
        DB::table('comunas')->insert(['nombre' =>'PICA', 'region_id' => 1]);
        DB::table('comunas')->insert(['nombre' =>'POZO ALMONTE', 'region_id' => 1]);
        DB::table('comunas')->insert(['nombre' =>'TOCOPILLA', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'ANTOFAGASTA', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'MEJILLONES', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'TALTAL', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'CALAMA', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'CHAÑARAL', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'DIEGO DE ALMAGRO', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'COPIAPO', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'CALDERA', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'TIERRA AMARILLA', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'VALLENAR', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'FREIRINA', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'HUASCO', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'LA SERENA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'LA HIGUERA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'COQUIMBO', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'ANDACOLLO', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'VICUÑA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'PAIHUANO', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'OVALLE', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'MONTE PATRIA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'PUNITAQUI', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'RIO HURTADO', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'COMBARBALA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'ILLAPEL', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'CANELA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'SALAMANCA', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'LOS VILOS', 'region_id' => 4]);
        DB::table('comunas')->insert(['nombre' =>'VALPARAISO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'QUINTERO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'PUCHUNCAVI', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'VIÑA DEL MAR', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'QUILPUE', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'VILLA ALEMANA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'CASABLANCA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'ISLA DE PASCUA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SAN ANTONIO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SANTO DOMINGO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'ALGARROBO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'EL QUISCO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'CARTAGENA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'EL TABO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'QUILLOTA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'LA CRUZ', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'LA CALERA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'HIJUELAS', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'NOGALES', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'LIMACHE', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'OLMUE', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'PETORCA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'CABILDO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'PAPUDO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'ZAPALLAR', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'LA LIGUA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SAN FELIPE', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'PUTAENDO', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'PANQUEHUE', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'CATEMU', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SANTA MARIA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'LLAY LLAY', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'LOS ANDES', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'CALLE LARGA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'RINCONADA', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SAN ESTEBAN', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SANTIAGO CENTRO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LAS CONDES', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PROVIDENCIA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SANTIAGO OESTE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CONCHALI', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'COLINA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'RENCA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LAMPA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'QUILICURA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'TIL-TIL', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'QUINTA NORMAL', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PUDAHUEL', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CURACAVI', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SANTIAGO SUR', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PEÑAFLOR', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'TALAGANTE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'ISLA DE MAIPO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'MELIPILLA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'EL MONTE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'MARIA PINTO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'ÑUÑOA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LA REINA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LA FLORIDA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'MAIPU', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SAN MIGUEL', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LA CISTERNA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LA GRANJA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SAN BERNARDO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CALERA DE TANGO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PUENTE ALTO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PIRQUE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SAN JOSE DE MAIPO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'BUIN', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PAINE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'RANCAGUA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'MACHALI', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'GRANEROS', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'SAN PEDRO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'ALHUE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CODEGUA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'SAN FRANCISCO DE MOSTAZAL', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'DOÑIHUE', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'COLTAUCO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'COINCO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PEUMO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'LAS CABRAS', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'SAN VICENTE', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PICHIDEGUA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'REQUINOA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'OLIVAR', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'RENGO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'MALLOA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'QUINTA DE TILCOCO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'SAN FERNANDO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'CHIMBARONGO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'NANCAGUA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PLACILLA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'SANTA CRUZ', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'LOLOL', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PALMILLA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PERALILLO', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'CHEPICA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PAREDONES', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'MARCHIGUE', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PUMANQUE', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'LITUECHE', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'PICHILEMU', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'NAVIDAD', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'LA ESTRELLA', 'region_id' => 6]);
        DB::table('comunas')->insert(['nombre' =>'CURICO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'ROMERAL', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'TENO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'RAUCO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'HUALAÑE', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'LICANTEN', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'VICHUQUEN', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'MOLINA', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'SAGRADA FAMILIA', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'RIO CLARO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'TALCA', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'SAN CLEMENTE', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'PELARCO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'PENCAHUE', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'MAULE', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'CUREPTO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'SAN JAVIER', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'CONSTITUCION', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'EMPEDRADO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'LINARES', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'YERBAS BUENAS', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'COLBUN', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'LONGAVI', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'VILLA ALEGRE', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'PARRAL', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'RETIRO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'CAUQUENES', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'CHANCO', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'CHILLAN', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'PINTO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'COIHUECO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'PORTEZUELO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'QUIRIHUE', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'TREHUACO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'NINHUE', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'COBQUECURA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN CARLOS', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN GREGORIO DE ÑIQUEN', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN FABIAN', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN NICOLAS', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'BULNES', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN IGNACIO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'QUILLON', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'YUNGAY', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'PEMUCO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'EL CARMEN', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'COELEMU', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'RANQUIL', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CONCEPCION', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'TALCAHUANO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'TOME', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'PENCO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'HUALQUI', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'FLORIDA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CORONEL', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'LOTA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SANTA JUANA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CURANILAHUE', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'ARAUCO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'LEBU', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'LOS ALAMOS', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CAÑETE', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CONTULMO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'TIRUA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'LOS ANGELES', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SANTA BARBARA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'QUILLECO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'YUMBEL', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CABRERO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'TUCAPEL', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'LAJA', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN ROSENDO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'NACIMIENTO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'NEGRETE', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'MULCHEN', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'QUILACO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'ANGOL', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'PUREN', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'LOS SAUCES', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'RENAICO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'COLLIPULLI', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'ERCILLA', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'TRAIGUEN', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'LUMACO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'VICTORIA', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'CURACAUTIN', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'LONQUIMAY', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'TEMUCO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'VILCUN', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'FREIRE', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'CUNCO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'LAUTARO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'GALVARINO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'PERQUENCO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'NUEVA IMPERIAL', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'CARAHUE', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'PUERTO SAAVEDRA', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'PITRUFQUEN', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'GORBEA', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'TOLTEN', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'LONCOCHE', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'VILLARRICA', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'PUCON', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'VALDIVIA', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'CORRAL', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'MARIQUINA', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'MAFIL', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'LOS LAGOS', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'FUTRONO', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'LANCO', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'PANGUIPULLI', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'LA UNION', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'PAILLACO', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'RIO BUENO', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'LAGO RANCO', 'region_id' => 14]);
        DB::table('comunas')->insert(['nombre' =>'OSORNO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PUYEHUE', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'SAN PABLO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PUERTO OCTAY', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'RIO NEGRO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PURRANQUE', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PUERTO MONTT', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'COCHAMO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'MAULLIN', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'LOS MUERMOS', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'CALBUCO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PUERTO VARAS', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'LLANQUIHUE', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'FRESIA', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'FRUTILLAR', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'CASTRO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'CHONCHI', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'QUEILEN', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'QUELLON', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PUQUELDON', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'QUINCHAO', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'CURACO DE VELEZ', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'ANCUD', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'QUEMCHI', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'DALCAHUE', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'CHAITEN', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'FUTALEUFU', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'PALENA', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'COYHAIQUE', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'AYSEN', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'CISNES', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'CHILE CHICO', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'RIO IBAÑEZ', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'COCHRANE', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'PUNTA ARENAS', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'PUERTO NATALES', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'PORVENIR', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'GENERAL LAGOS', 'region_id' => 15]);
        DB::table('comunas')->insert(['nombre' =>'PUTRE', 'region_id' => 15]);
        DB::table('comunas')->insert(['nombre' =>'CAMARONES', 'region_id' => 15]);
        DB::table('comunas')->insert(['nombre' =>'CAMINA', 'region_id' => 1]);
        DB::table('comunas')->insert(['nombre' =>'COLCHANE', 'region_id' => 1]);
        DB::table('comunas')->insert(['nombre' =>'MARIA ELENA', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'SIERRA GORDA', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'OLLAGÜE', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'SAN PEDRO DE ATACAMA', 'region_id' => 2]);
        DB::table('comunas')->insert(['nombre' =>'ALTO DEL CARMEN', 'region_id' => 3]);
        DB::table('comunas')->insert(['nombre' =>'ANTUCO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'MELIPEUCO', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'CURARREHUE', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'TEODORO SCHMIDT', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'SAN JUAN DE LA COSTA', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'HUALAIHUE', 'region_id' => 10]);
        DB::table('comunas')->insert(['nombre' =>'GUAITECAS', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'O´HIGGINS', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'TORTEL', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'LAGO VERDE', 'region_id' => 11]);
        DB::table('comunas')->insert(['nombre' =>'TORRES DEL PAINE', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'RIO VERDE', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'SAN GREGORIO', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'LAGUNA BLANCA', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'PRIMAVERA', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'TIMAUKEL', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'NAVARINO', 'region_id' => 12]);
        DB::table('comunas')->insert(['nombre' =>'PELLUHUE', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'JUAN FERNANDEZ', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'PEÑALOLEN', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'MACUL', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CERRO NAVIA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LO PRADO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SAN RAMON', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LA PINTANA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'ESTACION CENTRAL', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'RECOLETA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'INDEPENDENCIA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'VITACURA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LO BARNECHEA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CERRILLOS', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'HUECHURABA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'SAN JOAQUIN', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PEDRO AGUIRRE CERDA', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'LO ESPEJO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'EL BOSQUE', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'PADRE HURTADO', 'region_id' => 13]);
        DB::table('comunas')->insert(['nombre' =>'CONCON', 'region_id' => 5]);
        DB::table('comunas')->insert(['nombre' =>'SAN RAFAEL', 'region_id' => 7]);
        DB::table('comunas')->insert(['nombre' =>'CHILLAN VIEJO', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'SAN PEDRO DE LA PAZ', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'CHIGUAYANTE', 'region_id' => 8]);
        DB::table('comunas')->insert(['nombre' =>'PADRE LAS CASAS', 'region_id' => 9]);
        DB::table('comunas')->insert(['nombre' =>'ALTO HOSPICIO', 'region_id' => 1]);
    }
}
